# Generated by Django 4.2.8 on 2023-12-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_form_gender_alter_form_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='confirm_password',
            field=models.CharField(default='fghjj', max_length=100),
            preserve_default=False,
        ),
    ]
