# Generated by Django 4.2.8 on 2023-12-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userlogin_confirm_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='OrderForm',
        ),
    ]
